import Head from "next/head";
import AnimatedText from "~/components/AnimatedText";
import AnimatedTextWord from "~/components/AnimatedWord";
import Image from "next/image";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Formify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-1/3 absolute flex w-full flex-row overflow-y-hidden">
        <Box className="min-w-60 relative left-2 top-2 flex h-full w-1/2 flex-col overflow-visible p-4 sm:top-4 sm:left-4 md:top-8 md:left-8 lg:top-10 lg:left-10">
          <AnimatedText
            className={"cursor-pointer overflow-visible text-5xl text-black"}
            text={"FORMIFY"}
          />
          <AnimatedTextWord
            className={"mt-6 cursor-pointer flex-wrap text-4xl text-black"}
            text={"The easiest way to create an online form"}
          />
          <AnimatedTextWord
            className={"mt-12 cursor-pointer flex-wrap text-2xl text-black"}
            text={
              "Build forms in minutes instead of hours. The last form-builder you'll ever need."
            }
          />
        </Box>
        <Box className="relative -right-12 flex min-h-screen flex-col sm:-right-24 md:-right-32">
          <img
            src="/forms.jpg"
            className="min-h-screen w-auto"
            alt="formImage"
          />
        </Box>
      </main>
    </div>
  );
}
